#!/usr/bin/env python3
"""Minify webflow-embed-runtime.js for the Maxi embed export.

Outputs:
- webflow-embed-runtime.min.js       — the minified runtime itself
- webflow-embed-runtime.min.src.js   — sets window.FAL_EMBED_RUNTIME_MIN_SRC
  (minified source string) and window.FAL_EMBED_RUNTIME_MIN_GZB64
  (gzipped + base64 of the same, ~60% smaller — Maxi switches the embed to a
  self-extracting DecompressionStream loader when the plain runtime would
  push the snippet over Webflow's 50k limit, e.g. with inlined palette media);
  maxi.html loads this via a plain <script> tag so the export works even
  without a server (file:// blocks fetch).

Requires: python3 -m pip install --user rjsmin
"""

from __future__ import annotations

import base64
import json
import zlib
from pathlib import Path

from rjsmin import jsmin

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "webflow-embed-runtime.js"
DST_MIN = ROOT / "webflow-embed-runtime.min.js"
DST_SRC = ROOT / "webflow-embed-runtime.min.src.js"


def gzip_b64(text: str) -> str:
    # zlib with a gzip wrapper (16 + windowBits) and no mtime header noise,
    # so the output is deterministic run-to-run.
    comp = zlib.compressobj(9, zlib.DEFLATED, 16 + 15)
    data = comp.compress(text.encode("utf-8")) + comp.flush()
    return base64.b64encode(data).decode("ascii")


def main() -> None:
    source = SRC.read_text(encoding="utf-8")
    minified = jsmin(source).strip()
    DST_MIN.write_text(minified, encoding="utf-8")
    gz = gzip_b64(minified)
    # </script> inside the string literal would end the host script tag early.
    literal = json.dumps(minified).replace("</", "<\\/")
    DST_SRC.write_text(
        "// Generated by scripts/build-embed-runtime-min.py — do not edit.\n"
        "window.FAL_EMBED_RUNTIME_MIN_SRC = " + literal + ";\n"
        "window.FAL_EMBED_RUNTIME_MIN_GZB64 = " + json.dumps(gz) + ";\n",
        encoding="utf-8",
    )
    print(f"{SRC.name}: {len(source):,} chars")
    print(f"{DST_MIN.name}: {len(minified):,} chars ({len(minified) / len(source):.0%})")
    print(f"gzip+b64: {len(gz):,} chars ({len(gz) / len(minified):.0%} of minified)")
    print(f"{DST_SRC.name}: written")


if __name__ == "__main__":
    main()
